//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.07 at 06:01:41 PM EST 
//


package edu.stevens.cs594.chat.service.dto;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.UUID;


public class MessageDto
    implements Serializable
{

    private final static long serialVersionUID = 1L;

    protected UUID id;

    protected String text;
    protected String sender;
    protected OffsetDateTime timestamp;

    public UUID getId() {
        return id;
    }

    public void setId(UUID value) {
        this.id = value;
    }

    public boolean isSetId() {
        return true;
    }

    public String getText() {
        return text;
    }

    public void setText(String value) {
        this.text = value;
    }

    public boolean isSetText() {
        return (this.text!= null);
    }

    public String getSender() {
        return sender;
    }

    public void setSender(String value) {
        this.sender = value;
    }

    public boolean isSetSender() {
        return (this.sender!= null);
    }

    public OffsetDateTime getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(OffsetDateTime value) {
        this.timestamp = value;
    }

    public boolean isSetTimestamp() {
        return (this.timestamp!= null);
    }

    /*
     * To display timestamp, need to specify a time zone.  We use system default.
     */
    public ZonedDateTime getZonedTimestamp() {
        return timestamp.atZoneSameInstant(ZoneId.systemDefault());
    }

}
