//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.07 at 06:01:41 PM EST 
//


package edu.stevens.cs594.chat.service.dto;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


public class UserDto
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String username;
    protected String password;
    protected List<String> roles;
    protected String name;

    public String getUsername() {
        return username;
    }

    public void setUsername(String value) {
        this.username = value;
    }

    public boolean isSetUsername() {
        return (this.username!= null);
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String value) {
        this.password = value;
    }

    public boolean isSetPassword() {
        return (this.password!= null);
    }

    public List<String> getRoles() {
        if (roles == null) {
            roles = new ArrayList<String>();
        }
        return this.roles;
    }

    public boolean isSetRoles() {
        return ((this.roles!= null)&&(!this.roles.isEmpty()));
    }

    public void unsetRoles() {
        this.roles = null;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

}
